In [2]:
import numpy as np

A1=np.array([1,2,3,4,5])
print(type(A1))

<class 'numpy.ndarray'>


In [3]:
np.array([1,2,3,4.0])

array([1., 2., 3., 4.])

In [4]:
np.array([1,2,3,4.0,"a"])

array(['1', '2', '3', '4.0', 'a'], dtype='<U32')

In [12]:
# 2d array
arr=np.array([[1,2],[3,4]])
# to access array:
arr[0][1]

2

In [7]:
# 3d array
np.array([[[1,2],[3,4],[5,6]]])

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [8]:
# using ndmin function
np.array([1,2,3],ndmin=3)

array([[[1, 2, 3]]])

In [13]:
# for type casting we use dtype
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [14]:
# matrix
np.mat(arr)

matrix([[1, 2],
        [3, 4]])

In [15]:
# to convert list into array
l=[1,2,3,4]
np.array(l)

array([1, 2, 3, 4])

In [16]:
# to check the subclass
issubclass(np.matrix, np.ndarray)

True

In [28]:
A2=np.array([[1,2],[3,4]])
print(A2)

[[1 2]
 [3 4]]


In [ ]:
a=A2

In [ ]:
b=np.copy(A2)

In [ ]:
A2[0][0]=9

In [29]:
print(a)

[[9 2]
 [3 4]]


In [30]:
print(b)

[[9 2]
 [3 4]]


In [31]:
A2[0][1]=8
print(A2)

[[1 8]
 [3 4]]


In [32]:
print(b)

[[9 2]
 [3 4]]


In [34]:
# indexing & slicing are also perform on this
A2[-1]

array([3, 4])

In [35]:
# loops are also workin on this:
for i in A2:
    print(i)

[1 8]
[3 4]


In [36]:
np.fromfunction(lambda i, j :i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])