In [2]:
import numpy as np

A1=np.array([1,2,3,4,5])
print(type(A1))

<class 'numpy.ndarray'>


In [3]:
np.array([1,2,3,4.0])

array([1., 2., 3., 4.])

In [4]:
np.array([1,2,3,4.0,"a"])

array(['1', '2', '3', '4.0', 'a'], dtype='<U32')

In [12]:
# 2d array
arr=np.array([[1,2],[3,4]])
# to access array:
arr[0][1]

2

In [7]:
# 3d array
np.array([[[1,2],[3,4],[5,6]]])

array([[[1, 2],
        [3, 4],
        [5, 6]]])

In [8]:
# using ndmin function
np.array([1,2,3],ndmin=3)

array([[[1, 2, 3]]])

In [13]:
# for type casting we use dtype
np.array([1,2,3], dtype=float)

array([1., 2., 3.])

In [14]:
# matrix
np.mat(arr)

matrix([[1, 2],
        [3, 4]])

In [15]:
# to convert list into array
l=[1,2,3,4]
np.array(l)

array([1, 2, 3, 4])

In [16]:
# to check the subclass
issubclass(np.matrix, np.ndarray)

True

In [28]:
A2=np.array([[1,2],[3,4]])
print(A2)

[[1 2]
 [3 4]]


In [ ]:
a=A2

In [ ]:
b=np.copy(A2)

In [ ]:
A2[0][0]=9

In [29]:
print(a)

[[9 2]
 [3 4]]


In [30]:
print(b)

[[9 2]
 [3 4]]


In [31]:
A2[0][1]=8
print(A2)

[[1 8]
 [3 4]]


In [32]:
print(b)

[[9 2]
 [3 4]]


In [34]:
# indexing & slicing are also perform on this
A2[-1]

array([3, 4])

In [35]:
# loops are also workin on this:
for i in A2:
    print(i)

[1 8]
[3 4]


In [36]:
np.fromfunction(lambda i, j :i==j,(4,4))

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [2]:
gen=(i*i for i in range(5))
print(gen)

<generator object <genexpr> at 0x0000022F81754450>


In [5]:
import numpy as np
np.fromiter(gen, dtype=int)

array([ 0,  1,  4,  9, 16])

In [8]:
np.fromstring('1, 2, 3, 4', sep=",",dtype=int)

array([1, 2, 3, 4])

In [10]:
# to check the dimension
A3=np.array([[1,2],[3,4],[5,6]])
print(A3.ndim)
print(A3.size)
print(A3.shape)

2
6
(3, 2)


In [11]:
# arange function
np.arange(3.4)

array([0., 1., 2., 3.])

In [12]:
# linespace function:
np.linspace(1,2,5)

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [14]:
# zeros function:
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [16]:
# ones function:
np.ones((3,1))


array([[1.],
       [1.],
       [1.]])

In [18]:
# empty function:
np.empty((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [19]:
# eye function (identity matrix):
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [20]:
# logspace function:
np.logspace(2,3,4)

array([ 100.        ,  215.443469  ,  464.15888336, 1000.        ])

In [5]:
import numpy as np
D=np.eye(10)
print(D)
D.reshape(2,50)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]]


array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.,
        0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 1.]])

In [13]:
#rand function:
np.random.rand(3)

# randn function:
np.random.randn(5)

# randint function:
np.random.randint(2,5)

4

In [15]:
# max function:
ar=np.array([1,2,3,4,5,6])
ar.max()
ar.min()

1

In [23]:
# to extract data from numpy:
S=np.random.randint(2,10,(4,4))
print(S)
S[:2,:2]
S>10
S[S>10]

[[5 4 4 5]
 [7 9 4 6]
 [8 3 6 3]
 [5 4 4 6]]


array([], dtype=int32)

In [24]:
# * of array:
S*S

array([[25, 16, 16, 25],
       [49, 81, 16, 36],
       [64,  9, 36,  9],
       [25, 16, 16, 36]])

In [29]:
b=np.zeros((5,4))
b
b+2

array([[2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.],
       [2., 2., 2., 2.]])

In [30]:
b1=np.array([1,2,3,4])
b+b1

array([[1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.],
       [1., 2., 3., 4.]])

In [31]:
# transpose:
s1=np.array([[1,2,3]])
s1.T

array([[1],
       [2],
       [3]])

In [32]:
# for square root:
np.sqrt(s1)

array([[1.        , 1.41421356, 1.73205081]])

In [33]:
# for exponantial
np.exp(s1)

array([[ 2.71828183,  7.3890561 , 20.08553692]])

In [34]:
# for log values:
np.log10(s1)

array([[0.        , 0.30103   , 0.47712125]])